#!/usr/bin/env node
'use strict';

/**
 * generate-sw.js — post-build step
 *
 * Scans _site/, builds a URL list, computes a cache-version hash, then
 * writes _site/sw.js containing the full service-worker code with the
 * precache list embedded.
 *
 * Run after `eleventy` + `build:css` so every file is present.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const SITE_DIR = path.resolve(__dirname, '..', '_site');
const PATH_PREFIX = (process.env.PATH_PREFIX || '/').replace(/\/$/, ''); // '' or '/subpath'

// ── file scan ────────────────────────────────────────────────────────────────

function scanDir(dir) {
  const results = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...scanDir(full));
    else results.push(full);
  }
  return results;
}

function fileToUrl(filePath) {
  const rel = path.relative(SITE_DIR, filePath).replace(/\\/g, '/');
  const base = PATH_PREFIX + '/' + rel;
  if (rel === 'index.html') return PATH_PREFIX + '/';
  if (rel.endsWith('/index.html')) return base.slice(0, -'index.html'.length);
  return base;
}

const SKIP_FILES = new Set(['sw.js', '.gitkeep']);
const SKIP_EXTS = new Set(['.map']);

const allFiles = scanDir(SITE_DIR);

const entries = allFiles
  .map((f) => ({ file: f, url: fileToUrl(f) }))
  .filter(({ file, url }) => {
    if (SKIP_FILES.has(path.basename(file))) return false;
    if (SKIP_EXTS.has(path.extname(file))) return false;
    return true;
  });

// ── cache version ─────────────────────────────────────────────────────────────
// Hash over sorted (path, size, mtime) — changes whenever any file changes.

const hash = crypto.createHash('sha1');
for (const { file } of [...entries].sort((a, b) => a.file.localeCompare(b.file))) {
  const s = fs.statSync(file);
  hash.update(`${file}:${s.size}:${s.mtimeMs}`);
}
const cacheVersion = hash.digest('hex').slice(0, 10);

const urlList = entries.map((e) => e.url);

console.log(`[generate-sw] ${urlList.length} URLs → cache version ${cacheVersion}`);

// ── service worker source ─────────────────────────────────────────────────────

const sw = `/* Auto-generated by scripts/generate-sw.js — do not edit */
'use strict';

const CACHE_NAME = 'melimee-${cacheVersion}';

const PRECACHE_URLS = ${JSON.stringify(urlList, null, 2)};

// Extensions that compress well; everything else is stored as-is.
const COMPRESS_EXTS = new Set(['.html', '.css', '.js', '.json', '.svg', '.xml', '.txt']);
function shouldCompress(url) {
  const m = url.match(/\\.\\w+(?:[?#]|$)/);
  const ext = m ? m[0].replace(/[?#].*/, '') : '';
  return COMPRESS_EXTS.has(ext) || ext === ''; // no ext → likely an HTML page
}

const canCompress = typeof CompressionStream !== 'undefined';

// Compress an ArrayBuffer with gzip; returns { buffer, compressed }.
async function compress(buf) {
  if (!canCompress) return { buffer: buf, compressed: false };
  const cs = new CompressionStream('gzip');
  const w  = cs.writable.getWriter();
  w.write(buf);
  w.close();
  return { buffer: await new Response(cs.readable).arrayBuffer(), compressed: true };
}

// Decompress a cached Response if we compressed it on the way in.
async function maybeDecompress(res) {
  if (!res || !res.headers.get('X-SW-Compressed')) return res;
  const ds = new DecompressionStream('gzip');
  const w  = ds.writable.getWriter();
  w.write(await res.arrayBuffer());
  w.close();
  const headers = new Headers(res.headers);
  headers.delete('X-SW-Compressed');
  return new Response(ds.readable, { status: res.status, statusText: res.statusText, headers });
}

// Fetch one URL and store it in the cache (compressing text content).
async function fetchAndCache(cache, url) {
  try {
    const res = await fetch(url, { cache: 'no-cache' });
    if (!res.ok) return;
    if (shouldCompress(url)) {
      const body = await res.arrayBuffer();
      const { buffer, compressed } = await compress(body);
      const headers = new Headers(res.headers);
      if (compressed) headers.set('X-SW-Compressed', '1');
      await cache.put(url, new Response(buffer, { status: res.status, statusText: res.statusText, headers }));
    } else {
      await cache.put(url, res);
    }
  } catch (e) {
    console.warn('[SW] cache miss:', url, e.message);
  }
}

// ── lifecycle ─────────────────────────────────────────────────────────────────

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    const BATCH = 10;
    for (let i = 0; i < PRECACHE_URLS.length; i += BATCH) {
      await Promise.all(PRECACHE_URLS.slice(i, i + BATCH).map(url => fetchAndCache(cache, url)));
    }
    self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)));
    self.clients.claim();
  })());
});

// ── fetch strategy: cache-first, network fallback ─────────────────────────────

self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  event.respondWith((async () => {
    const cached = await caches.match(event.request);
    if (cached) return maybeDecompress(cached);
    try {
      return await fetch(event.request);
    } catch {
      return new Response('Hors-ligne', { status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
    }
  })());
});
`;

fs.writeFileSync(path.join(SITE_DIR, 'sw.js'), sw, 'utf8');
console.log('[generate-sw] wrote _site/sw.js');
